services:
  slurmfrontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        image: ghcr.io/noaa-gsl/dockerslurmcluster/slurm-frontend:latest
        container_name: slurm-frontend
        shm_size: '4g'
        hostname: slurmfrontend
        user: admin
        volumes:
                - shared-vol:/home/admin
        ports:
                - 8888:8888
  slurmmaster:
        build:
          context: ./master
          dockerfile: Dockerfile
        image: ghcr.io/noaa-gsl/dockerslurmcluster/slurm-master:latest
        container_name: slurm-master
        shm_size: '4g'
        hostname: slurmmaster
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
        environment:
                - SLURM_CPUS_ON_NODE=8
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
        build:
          context: ./node
          dockerfile: Dockerfile
        image: ghcr.io/noaa-gsl/dockerslurmcluster/slurm-node:latest
        container_name: slurm-node1
        shm_size: '4g'
        hostname: slurmnode1
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
        environment:
                - SLURM_NODENAME=slurmnode1
                - SLURM_CPUS_ON_NODE=8
        links:
                - slurmmaster
  slurmnode2:
        build:
          context: ./node
          dockerfile: Dockerfile
        image: ghcr.io/noaa-gsl/dockerslurmcluster/slurm-node:latest
        container_name: slurm-node2
        shm_size: '4g'
        hostname: slurmnode2
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
        environment:
                - SLURM_NODENAME=slurmnode2
                - SLURM_CPUS_ON_NODE=8
        links:
                - slurmmaster
  slurmnode3:
        build:
          context: ./node
          dockerfile: Dockerfile
        image: ghcr.io/noaa-gsl/dockerslurmcluster/slurm-node:latest
        container_name: slurm-node3
        shm_size: '4g'
        hostname: slurmnode3
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
        environment:
                - SLURM_NODENAME=slurmnode3
                - SLURM_CPUS_ON_NODE=8
        links:
                - slurmmaster
volumes:
        shared-vol:
